# Generated by Django 2.2.10 on 2021-06-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('user_poll', 'question'), name='question_user_poll'),
        ),
    ]
